### ISSUE TITLE
What  to use as a RF Choke across J4-J7 

### ISSUE THREAD

**Issue by geekbozu** [profdc9/VNA#1]
What to use and how to wire up this choke for decent performance?

**Comment by profdc9** [comment]
Use a small toroid something like two stacked FT50-43 four turns through it, with J4-J6 and J5-J7 connected together through the choke.  I used a ferrite that was like a FT50-75 and that seemed to work as well.  75/77 works better at lower frequencies, 43 on higher, but it's a common mode choke so its pretty tolerant.

**Comment by geekbozu** [comment]
Would there be any issues just leaving it out? I feel like this may be unnecessary/really hurting higher frequency performance. Maybe adding a 500mhz LowPass would perform similarly with out causing Loss on the higher frequencies?

**Comment by profdc9** [comment]
The common mode choke is needed to generate a voltage on the current sense
resistor proportional to the current in the port.  The VNA will not
function without it.  Even a simple choke is better than none.  Some have
actually used the ferrite bead taken from an EMI suppressor in a cable.

Dan

**Comment by geekbozu** [comment]
I had a conversation with EU1KY my problem has been solved. Will close for now and respond with info after testing.
